//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicketMobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETicketMobile.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        internal static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send activation code.
        /// </summary>
        internal static string ActivationCodeAgain1 {
            get {
                return ResourceManager.GetString("ActivationCodeAgain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to again..
        /// </summary>
        internal static string ActivationCodeAgain2 {
            get {
                return ResourceManager.GetString("ActivationCodeAgain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next time you can call it in.
        /// </summary>
        internal static string ActivationCodeTimerText {
            get {
                return ResourceManager.GetString("ActivationCodeTimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string AlreadySignUp {
            get {
                return ResourceManager.GetString("AlreadySignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ticket.
        /// </summary>
        internal static string BuyTicket {
            get {
                return ResourceManager.GetString("BuyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card expiration.
        /// </summary>
        internal static string CardExpiration {
            get {
                return ResourceManager.GetString("CardExpiration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter cancel.
        /// </summary>
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the correct card numbers.
        /// </summary>
        internal static string CardNumberCorrect {
            get {
                return ResourceManager.GetString("CardNumberCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok
        {
            get
            {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter activation code.
        /// </summary>
        internal static string ConfirmEmailEmpty {
            get {
                return ResourceManager.GetString("ConfirmEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address and we will send you the code for recovery access to your account.
        /// </summary>
        internal static string ConfirmEmailForRecovery {
            get {
                return ResourceManager.GetString("ConfirmEmailForRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong activation code.
        /// </summary>
        internal static string ConfirmEmailWrong {
            get {
                return ResourceManager.GetString("ConfirmEmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose ticket.
        /// </summary>
        internal static string CountTicketsWrong {
            get {
                return ResourceManager.GetString("CountTicketsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new password.
        /// </summary>
        internal static string CreateNewPassword {
            get {
                return ResourceManager.GetString("CreateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        internal static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description payment.
        /// </summary>
        internal static string DescriptionPayment {
            get {
                return ResourceManager.GetString("DescriptionPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you entered your email correctly?.
        /// </summary>
        internal static string EmailCorrect {
            get {
                return ResourceManager.GetString("EmailCorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account
        {
            get
            {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, your username must be fewer than 50 characters long..
        /// </summary>
        internal static string EmailCorrectLong {
            get {
                return ResourceManager.GetString("EmailCorrectLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email.
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use letters, numbers &amp; periods.
        /// </summary>
        internal static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an email address.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is taken. Try another..
        /// </summary>
        internal static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exists.
        /// </summary>
        internal static string EmailWarning {
            get {
                return ResourceManager.GetString("EmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with that username doesn&apos;t exists..
        /// </summary>
        internal static string EmailWrong {
            get {
                return ResourceManager.GetString("EmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your date of birth.
        /// </summary>
        internal static string EnterBirthday {
            get {
                return ResourceManager.GetString("EnterBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name. You can change it in any time..
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone.
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify expiration code.
        /// </summary>
        internal static string ExpirationDateCorrect {
            get {
                return ResourceManager.GetString("ExpirationDateCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/YY.
        /// </summary>
        internal static string ExpirationYear {
            get {
                return ResourceManager.GetString("ExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        internal static string FirstNameEmpty {
            get {
                return ResourceManager.GetString("FirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstNameHint {
            get {
                return ResourceManager.GetString("FirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you entered your first name correctly?.
        /// </summary>
        internal static string FirstNameValid {
            get {
                return ResourceManager.GetString("FirstNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate password.
        /// </summary>
        internal static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check your network connection and try again.
        /// </summary>
        internal static string ErrorConnection
        {
            get
            {
                return ResourceManager.GetString("ErrorConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We will remember your data for sign in, and you dont need anymore to fill it again.
        /// </summary>
        internal static string GeneratePasswordHint {
            get {
                return ResourceManager.GetString("GeneratePasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        internal static string LastNameEmpty {
            get {
                return ResourceManager.GetString("LastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastNameHint {
            get {
                return ResourceManager.GetString("LastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you entered your last name correctly?.
        /// </summary>
        internal static string LastNameValid {
            get {
                return ResourceManager.GetString("LastNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizations.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tickets.
        /// </summary>
        internal static string MyTickets {
            get {
                return ResourceManager.GetString("MyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 100 characters or fewer for your password.
        /// </summary>
        internal static string PasswordLong {
            get {
                return ResourceManager.GetString("PasswordLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordWatermarkDefault {
            get {
                return ResourceManager.GetString("PasswordWatermarkDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or wrong password.
        /// </summary>
        internal static string PasswordWatermarkWrong {
            get {
                return ResourceManager.GetString("PasswordWatermarkWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 8 characters or more for your password.
        /// </summary>
        internal static string PasswordShort {
            get {
                return ResourceManager.GetString("PasswordShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, make sure your passwords match.
        /// </summary>
        internal static string PasswordsMatch {
            get {
                return ResourceManager.GetString("PasswordsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 8 or more characters with a mix of letters, numbers &amp; symbols.
        /// </summary>
        internal static string PasswordStandartFormat {
            get {
                return ResourceManager.GetString("PasswordStandartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose a stronger password. Try a mix of letters, numbers, symbols..
        /// </summary>
        internal static string PasswordStrong {
            get {
                return ResourceManager.GetString("PasswordStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By pressing the button «Pay» you accept.
        /// </summary>
        internal static string PayAccept {
            get {
                return ResourceManager.GetString("PayAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string PayButton {
            get {
                return ResourceManager.GetString("PayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be in format +380 (XX)-XXX-XX-XX.
        /// </summary>
        internal static string PhoneFormat {
            get {
                return ResourceManager.GetString("PhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string RegistrationHint {
            get {
                return ResourceManager.GetString("RegistrationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions History.
        /// </summary>
        internal static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t you sign in?.
        /// </summary>
        internal static string WrongSignIn {
            get {
                return ResourceManager.GetString("WrongSignIn", resourceCulture);
            }
        }
    }
}
